-- Game Scoreboard - chạy toàn bộ file này trong Supabase SQL Editor.
-- Public được xem; chỉ tài khoản đã đăng nhập mới được sửa dữ liệu.

create table if not exists public.players (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 60),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create unique index if not exists players_name_unique
  on public.players (lower(trim(name)));

create table if not exists public.tours (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 100),
  game_key text not null default 'ta_la' constraint tours_game_key_length check (char_length(trim(game_key)) between 1 and 60),
  played_on date not null default current_date,
  created_at timestamptz not null default now()
);

alter table if exists public.tours
  add column if not exists game_key text not null default 'ta_la';

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'tours_game_key_length'
      and conrelid = 'public.tours'::regclass
  ) then
    alter table public.tours
      add constraint tours_game_key_length check (char_length(trim(game_key)) between 1 and 60);
  end if;
end;
$$;

create table if not exists public.tour_players (
  tour_id bigint not null references public.tours(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete restrict,
  primary key (tour_id, player_id)
);

create table if not exists public.games (
  id bigint generated by default as identity primary key,
  tour_id bigint not null references public.tours(id) on delete cascade,
  game_number integer not null check (game_number > 0),
  created_at timestamptz not null default now(),
  unique (tour_id, game_number)
);

create table if not exists public.game_scores (
  game_id bigint not null references public.games(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete restrict,
  score integer not null,
  primary key (game_id, player_id)
);

create index if not exists games_tour_id_idx on public.games(tour_id);
create index if not exists game_scores_player_id_idx on public.game_scores(player_id);

alter table public.players enable row level security;
alter table public.tours enable row level security;
alter table public.tour_players enable row level security;
alter table public.games enable row level security;
alter table public.game_scores enable row level security;

-- Cho mọi người xem bảng điểm.
drop policy if exists "public read players" on public.players;
create policy "public read players" on public.players for select using (true);
drop policy if exists "public read tours" on public.tours;
create policy "public read tours" on public.tours for select using (true);
drop policy if exists "public read tour_players" on public.tour_players;
create policy "public read tour_players" on public.tour_players for select using (true);
drop policy if exists "public read games" on public.games;
create policy "public read games" on public.games for select using (true);
drop policy if exists "public read game_scores" on public.game_scores;
create policy "public read game_scores" on public.game_scores for select using (true);

-- Tài khoản đăng nhập được quản trị.
drop policy if exists "admin write players" on public.players;
create policy "admin write players" on public.players for all to authenticated
  using (true) with check (true);
drop policy if exists "admin write tours" on public.tours;
create policy "admin write tours" on public.tours for all to authenticated
  using (true) with check (true);
drop policy if exists "admin write tour_players" on public.tour_players;
create policy "admin write tour_players" on public.tour_players for all to authenticated
  using (true) with check (true);
drop policy if exists "admin write games" on public.games;
create policy "admin write games" on public.games for all to authenticated
  using (true) with check (true);
drop policy if exists "admin write game_scores" on public.game_scores;
create policy "admin write game_scores" on public.game_scores for all to authenticated
  using (true) with check (true);

-- Lưu mới hoặc sửa một game trong một transaction.
-- Database tự kiểm tra: đủ người, điểm nguyên, người thuộc tour, tổng bằng 0.
create or replace function public.save_game(
  p_tour_id bigint,
  p_scores jsonb,
  p_game_id bigint default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_game_id bigint;
  v_score_count integer;
  v_distinct_count integer;
  v_score_total bigint;
  v_invalid_players integer;
  v_tour_player_count integer;
begin
  if auth.uid() is null then
    raise exception 'Bạn cần đăng nhập để lưu điểm.';
  end if;

  if not exists (select 1 from tours where id = p_tour_id) then
    raise exception 'Tour không tồn tại.';
  end if;

  if jsonb_typeof(p_scores) <> 'array' then
    raise exception 'Dữ liệu điểm không hợp lệ.';
  end if;

  select count(*), count(distinct player_id), coalesce(sum(score), 0)
  into v_score_count, v_distinct_count, v_score_total
  from jsonb_to_recordset(p_scores) as x(player_id bigint, score integer);

  if v_score_count < 2 then
    raise exception 'Mỗi ván cần ít nhất 2 người.';
  end if;
  if v_score_count <> v_distinct_count then
    raise exception 'Một người đang bị nhập điểm nhiều lần.';
  end if;
  if v_score_total <> 0 then
    raise exception 'Tổng điểm mỗi ván phải bằng 0 (hiện tại: %).', v_score_total;
  end if;

  select count(*) into v_invalid_players
  from jsonb_to_recordset(p_scores) as x(player_id bigint, score integer)
  where not exists (
    select 1 from tour_players tp
    where tp.tour_id = p_tour_id and tp.player_id = x.player_id
  );
  if v_invalid_players > 0 then
    raise exception 'Có người chơi không thuộc tour này.';
  end if;

  select count(*) into v_tour_player_count
  from tour_players where tour_id = p_tour_id;
  if v_score_count <> v_tour_player_count then
    raise exception 'Cần nhập điểm cho tất cả người chơi trong tour.';
  end if;

  if p_game_id is null then
    insert into games (tour_id, game_number)
    values (
      p_tour_id,
      coalesce((select max(game_number) + 1 from games where tour_id = p_tour_id), 1)
    ) returning id into v_game_id;
  else
    select id into v_game_id from games
    where id = p_game_id and tour_id = p_tour_id
    for update;
    if v_game_id is null then
      raise exception 'Game không tồn tại trong tour này.';
    end if;
    delete from game_scores where game_id = v_game_id;
  end if;

  insert into game_scores (game_id, player_id, score)
  select v_game_id, x.player_id, x.score
  from jsonb_to_recordset(p_scores) as x(player_id bigint, score integer);

  return v_game_id;
end;
$$;

revoke all on function public.save_game(bigint, jsonb, bigint) from public;
grant execute on function public.save_game(bigint, jsonb, bigint) to authenticated;

-- Xoá game và đánh lại số thứ tự trong cùng tour.
create or replace function public.delete_game(p_game_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tour_id bigint;
begin
  if auth.uid() is null then
    raise exception 'Bạn cần đăng nhập để xoá game.';
  end if;
  select tour_id into v_tour_id from games where id = p_game_id;
  if v_tour_id is null then
    raise exception 'Game không tồn tại.';
  end if;
  delete from games where id = p_game_id;
  -- Dời số hiện tại lên vùng tạm dương để không đụng unique/check constraint.
  update games set game_number = game_number + 1000000 where tour_id = v_tour_id;
  with numbered as (
    select id, row_number() over (order by game_number, created_at, id)::integer as new_number
    from games where tour_id = v_tour_id
  )
  update games g set game_number = n.new_number
  from numbered n where g.id = n.id;
end;
$$;

revoke all on function public.delete_game(bigint) from public;
grant execute on function public.delete_game(bigint) to authenticated;
